@extends('layouts.master')

@section('title')
Privacy & Policy
@endsection


@section('main-content')
<section>
    <h1 class="title">Privacy & Policy</h1>
    <div class="roboto-slab info-section" style="font-size: 14px;">
        <div style="margin-bottom: 30px;">
            <strong>MyC2I and its parent company DINA, LLC.</strong> ("Company") understands the importance of online privacy. The following Policy outlines how we do business, what information we collect and how, under what circumstances the information is shared with third parties, and your options to control what communications you receive from us and other users of this site. If you have any questions or concerns about this Privacy Policy, please contact us.
        </div>
        <div style="margin-top: 50px;">
            <h3 class="section-title">Information We Collect And How It Is Used</h3>
            <p>In order to participate in this Islamic mentor-guest network, you must first complete the sign up information requested. We ask for an email address so that we can deliver messages generated by the MyC2i website and so we may contact you if necessary. We ask for a mailing address so we know where to ship the products that you may have purchased pertaining to training. We ask for a phone number if you wish to be contacted by phone. The system will not display your email address or phone number to any other user.</p>
            <p>Registering for this network automatically subscribes you to the MyC2I newsletter, a periodic email communicating various news and updates that we think you might like based on the sign up information you provided. Users may unsubscribe from this newsletter an any time by clicking on the automated link provided on the sign up or personal information page.</p>
            <p>We request a limited amount of personally identifiable information from users who participate in the network on this site. This information includes, but is not limited to the following:</p>
            <ul>
                <li>email address</li>
                <li>name</li>
                <li>address, city, state, zip</li>
                <li>phone number</li>
            </ul>
            <p>We use this information to communicate with you about the status of your quest for Islamic knowledge, mentor-guest and how your mentor-guest relationship is developing. We request your address and phone number for shipping purposes and customer support issues.<p>

            <p>We use information provided by our users to enhance their experience on this and similar Web sites. We also use the information provided voluntarily to send out electronic mailings to possible mentor-guest matches that we think will be of benefit to you. At all times, Users have the option to unsubscribe from such mailings by clicking on the unsubscribe link provided on sign up and personal information page.<p>

            <p>We create internal reports on user demographics and traffic patterns to measure the effectiveness of our mentor-guest matching programs, and to analyze results. We do use any personally identifiable information to compile these reports.<p>
        </div>
        <div style="margin-top: 50px;">
            <h3 class="section-title">How We Collect Information</h3>
            <p><i>The Company gathers information in the following ways:</i></p>
        </div>
        <div style="margin-top: 50px;">
            <h3 class="section-title">Cookies</h3>
            <p>A cookie is a small text file stored on a user's computer for record-keeping purposes. The Company uses cookies only to enable users to be routed properly through our site. We encourage our users to be aware of the individual privacy policies of every Web site that the user contacts.</p>
        </div>
        <div style="margin-top: 50px;">
            <h3 class="section-title">Clear Gif's (Web Beacons/Web Bugs)</h3>
            <p>The Company may also use a software technology called clear gif's (Web Beacons or Web Bugs), that help us determine what content on our site is most effective. Clear gif's are tiny graphics with a unique identifier, similar in function to cookies, and are used to track the online movements of Web users. We do not tie the information gathered by clear gif's to our customers' personally identifiable information.</p>
            <p>We also use clear gif's in our HTML-based emails so that we know which emails have been opened. We use this information to monitor the effectiveness of our email campaigns and to validate our results.</p>
        </div>
        <div style="margin-top: 50px;">
            <h3 class="section-title">Log Files</h3>
            <p>Log files are also used to track and monitor traffic patterns on our site. They are not used to track or monitor personally identifiable information.</p>
        </div>
        <div style="margin-top: 50px;">
            <h3 class="section-title">Tell-A-Friend</h3>
            <p>Users may forward the email address of another person who may also be interested in this particular network. The information is used only to forward the information to that person and is not retained for any other purpose.</p>
        </div>
        <div style="margin-top: 50px;">
            <h3 class="section-title">User Feedback/Inquiries</h3>
            <p>Users may contact the Company with any feedback, questions or comments. The Company uses contact information only to respond to the feedback.</p>
        </div>
        <div style="margin-top: 50px;">
            <h3 class="section-title">Other Circumstances</h3>
            <p>Subsequent to this network, the Company may sponsor contests or other events for which we need to collect and retain personally identifiable information. The Company may co-sponsor such events with other companies.</p>
        </div>
        <div style="margin-top: 50px;">
            <h3 class="section-title">Information We Share</h3>
            <p>This Privacy Policy applies to consumers that have signed up on the MyC2I website. We do NOT sell, brand nor share your personal information that you supply to us with other 3rd party businesses.</p>
        </div>
        <div style="margin-top: 50px;">
            <h3 class="section-title">Use of Information</h3>
            <p>This Privacy Policy applies to consumers that have signed up on the MyC2I website, and or have submitted their email address through our affiliate network program and other partnerships to promote our site. We will not use the personal information that you supply to us and work with other third party businesses.</p>
        </div>
        <div style="margin-top: 50px;">
            <h3 class="section-title">Delete/Deactivate Policy</h3>
            <p>Users at any time may unsubscribe to our electronic mailings by following the instructions that we include on the sign up and personal info pages. To correct, update or request that we delete information you provided, please contact us via email</p>
            <p><i>info@MyC2I.org</i></p>
            <p><strong>You can unsubscribe at any time by editing your profile from my account option</strong></p>
        </div>
        <div style="margin-top: 50px;">
            <h3 class="section-title">Notification Of Changes To Privacy Policy</h3>
            <p>From time to time, we may use customer information for new, unanticipated uses not previously disclosed in our privacy notice. If our information practices change at some time in the future we will post these policy changes to our Web site to notify you and provide you with the opportunity to opt out of these new uses. If you are concerned about how your information is used, you should check back at our Web site periodically.</p>
        </div>
        <div style="margin-top: 50px;">
            <h3 class="section-title">General Security Policy</h3>
            <p>The Company endeavors at all times to meet and exceed standards of online privacy protection. When you submit information, your information is protected both on-line and off-line in accordance with applicable laws, regulations and industry standards. For example, without limitation, the company uses a full-time Network Administrator, SSL servers, pgp and 128-bit encryption to protect the confidentiality of the information you provide.</p>
            <p>For additional information or specific questions, please contact us.</p>
            <p>MyC2I is an independent organization for people of various faiths to network with existing Muslims.</p>
        </div>
    </div>
</section>

<style>
    .info-section {
        text-align: left!important;
        background-color: #f8f8f8;
        padding: 50px;
        border-radius: 10px;
    }
    .section-title {
        color: #441a05;
        font-family: 'Cinzel Decorative', cursive;
        font-size: 21px;
        text-align: left!important;
    }
    .section-sub-title {
        color: #441a05;
        font-size: 16px;
    }
</style>
@endsection
